# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
target 'OyeSpace' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   #use_frameworks!
  
  # Pods for OyeSpace
 
 pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'




  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
 
  
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  

  pod 'Firebase/Core', '~> 5.19.0'
  pod 'Firebase/Messaging', '~> 5.19.0'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'RNFirebase/Crashlytics', :path => '../node_modules/react-native-firebase/ios'
  
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  
    pod 'RNShare', :path => '../node_modules/react-native-share'
  
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  
  
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker/RNDateTimePicker.podspec'

  

  #pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'
  
  pod 'Fabric'
  pod 'Crashlytics'
  
  


  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  
  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'


  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'
  
  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
#


  

  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

  pod 'RNAudioRecorderPlayer', :path => '../node_modules/react-native-audio-recorder-player'


  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RCTSystemSetting', :path => '../node_modules/react-native-system-setting'

  pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'
  

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  #pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'
  


  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-html-to-pdf', :path => '../node_modules/react-native-html-to-pdf'

  pod 'RNImageToPdf', :path => '../node_modules/react-native-image-to-pdf'

 pod 'RNSound',
 :path => "../node_modules/react-native-sound"


  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'
  
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'

  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

  pod 'react-native-location-satellites', :path => '../node_modules/react-native-location-satellites'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'


  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'
  
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'


    pod 'react-native-get-random-values', :path => '../node_modules/react-native-get-random-values'

  end

def main_pods
end
post_install do |installer_representation|
end
  
#post_install do |installer|
#installer.pods_project.targets.each do |target|
#  if target.name == "React"
#    target.remove_from_project
#  end
#end
#
#post_install do |installer|
#  rnfirebase = installer.pods_project.targets.find { |target| target.name == 'RNFirebase' }
#  rnfirebase.build_configurations.each do |config|
#    config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
#  end
#end
#end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == 'react-native-google-maps'
#       target.build_configurations.each do |config|
#         config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
#       end
#     end
#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#
#     # The following is needed to ensure the "archive" step works in XCode.
#     # It removes React & Yoga from the Pods project, as it is already included in the main project.
#     # Without this, you'd see errors when you archive like:
#     # "Multiple commands produce ... libReact.a"
#     # "Multiple commands produce ... libyoga.a"
#
#     targets_to_ignore = %w(React yoga)
#
#     if targets_to_ignore.include? target.name
#       target.remove_from_project
#     end
#
#   end
# end

