# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
target 'OyeSpace' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for OyeSpace
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  'CxxBridge',
  'DevSupport'
  ]



  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'



  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
 
  
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  

  pod 'Firebase/Core', '~> 5.19.0'
  pod 'Firebase/Messaging', '~> 5.19.0'
  
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  
  #  pod 'RNShare', :path => '../node_modules/react-native-share'
  
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  
  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'
  
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  

  #pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'
  
  pod 'Fabric'
  pod 'Crashlytics'
  
  # Third party deps podspec link
  #  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  # pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  # pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  # pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  # pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  # pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  # pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  # pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  # pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  # pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  # pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  


  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'


  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'
  
  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
#


  

  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

  pod 'RNAudioRecorderPlayer', :path => '../node_modules/react-native-audio-recorder-player'


 # pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RCTSystemSetting', :path => '../node_modules/react-native-system-setting'

  pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'
  

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'
  



#  pod 'react-native-location-satellites', :path => '../node_modules/react-native-location-satellites'

end
  
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == 'react-native-google-maps'
#       target.build_configurations.each do |config|
#         config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
#       end
#     end
#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#
#     # The following is needed to ensure the "archive" step works in XCode.
#     # It removes React & Yoga from the Pods project, as it is already included in the main project.
#     # Without this, you'd see errors when you archive like:
#     # "Multiple commands produce ... libReact.a"
#     # "Multiple commands produce ... libyoga.a"
#
#     targets_to_ignore = %w(React yoga)
#
#     if targets_to_ignore.include? target.name
#       target.remove_from_project
#     end
#
#   end
# end
