export const Fonts = {
    OpenSansBold : 'Pacifico-OpenSans-Bold',
    OpenSansBoldItalic: 'OpenSans-BoldItalic',
    OpenSansExtraBold :'OpenSans-ExtraBold',
    OpenSansExtraBoldItalic : 'OpenSans-ExtraBoldItalic',
    OpenSansItalic : 'OpenSans-Italic',
    OpenSansLight : 'OpenSans-Light',
    OpenSansLightItalic : 'OpenSans-LightItalic',
    OpenSansRegular : 'OpenSans-Regular',
    OpenSansSemiBold : 'OpenSans-SemiBold',
    OpenSansSemiBoldItalic : 'OpenSans-SemiBoldItalic',
    PacificoRegular : 'Pacifico-Regular',
    JosefinSansBold : 'JosefinSans-Bold',
    JosefinSansRegular : 'JosefinSans-Regular',
    PoppinsBold : 'Poppins-Bold',
    PoppinsExtraBold : 'Poppins-ExtraBold',
    PoppinsLight : 'Poppins-Light',
    PoppinsRegular : 'Poppins-Regular',

}